### ISSUE TITLE
SBT file must only contain expressions

### ISSUE THREAD

**Issue by nermin** [JetBrains/intellij-sbt#8]
My ```build.sbt``` file in a Play project contains the following line:
```
lazy val root = (project in file(".")).enablePlugins(PlayScala)
```
That is underlined in red, with an error: "SBT file must only contain expressions"

IntelliJ IDEA 14.0.2
Build #IC-139.659
Scala plugin version: 1.2.1

**Comment by magic890** [comment]
Same problem on IntelliJ IDEA 14.1.2.

**Comment by tferi** [comment]
Same in current 15 EAP (built on July 21)

**Comment by dancingrobot84** [comment]
@magic890 @tferi Could you please tell me what operation system do you use?

**Comment by tferi** [comment]
OS X 10.10.3 (14D131)

**Comment by dancingrobot84** [comment]
@tferi Could you please attach screenshot of a IDEA's Project Structure window on "Modules" tab?

**Comment by tferi** [comment]
![image](https://cloud.githubusercontent.com/assets/4521356/8850992/b0e10630-314c-11e5-9718-7b2b58fc7eda.png)

There you go!

**Comment by dancingrobot84** [comment]
@tferi Thanks! It seems like your project is incorrectly imported. Could you please attach your build.sbt and other build files (*.sbt, project/*.sbt and project/*.scala)?

**Comment by tferi** [comment]
You were right, re-importing the project fixed the problem. I may have migrated a project generated with sbt-idea for IDEA 13 instead of importing it cleanly, I don't remember.
